Lab1

Mau 1

In [1]:
import numpy as np
import pandas as pd

my_list = [1,9,15,39]
print('Python list: ', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]

Bai 1:

In [2]:
import numpy as np

random_array = np.random.randint(0,21,size=(3,3))
print("Mang ngau nhien 3x3:")
print(random_array)
all_non_zero = np.all(random_array !=0)

print("\nTat ca cac phan tu trong mang khac 0: ", all_non_zero)

Mang ngau nhien 3x3:
[[ 9 13 13]
 [10 18  7]
 [10  2  1]]

Tat ca cac phan tu trong mang khac 0:  True

Bai 2:

In [3]:
import numpy as np

# Tạo mảng 2 chiều 3x3 với các số nguyên ngẫu nhiên trong khoảng [0, 20]
random_array_2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên 3x3:")
print(random_array_2)

# Kiểm tra tồn tại ít nhất một phần tử khác 0
has_non_zero = np.any(random_array_2 != 0)

print("\nTồn tại ít nhất một phần tử khác 0:", has_non_zero)

Mảng ngẫu nhiên 3x3:
[[11  3 11]
 [20 15  0]
 [ 5 19  2]]

Tồn tại ít nhất một phần tử khác 0: True

Bai 3

In [ ]:
import numpy as np

# 1. So sánh mảng 1 chiều
a = np.array([1, 5, 10])
b = np.array([1, 2, 12])

print("Mảng 1 chiều a:", a)
print("Mảng 1 chiều b:", b)
print("a > b (greater):", np.greater(a, b))
print("a >= b (greater_equal):", np.greater_equal(a, b))
print("a < b (less):", np.less(a, b))
print("a <= b (less_equal):", np.less_equal(a, b))

# 2. So sánh mảng 2 chiều
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 2], [4, 4]])

print("\nMảng 2 chiều A:\n", A)
print("Mảng 2 chiều B:\n", B)
print("A > B:\n", np.greater(A, B))
print("A >= B:\n", np.greater_equal(A, B))
print("A < B:\n", np.less(A, B))
print("A <= B:\n", np.less_equal(A, B))

Bai 4

In [ ]:
import numpy as np

# Tạo mảng gồm 10 số 0, 10 số 1 và 10 số 5
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.ones(10) * 5

# Kết hợp các mảng lại với nhau
result = np.concatenate([ones, zeros, fives])

print("Mảng kết quả:")
print(result)

Bai 5

In [ ]:
import numpy as np

# Tạo mảng số nguyên chẵn từ 30 đến 70
# np.arange(start, stop, step) - stop không bao gồm giá trị cuối nên dùng 71
even_array = np.arange(30, 71, 2)

print("Mảng số nguyên chẵn từ 30 đến 70:")
print(even_array)

Bai 6

In [ ]:
import numpy as np

# Tạo ma trận đơn vị 3x3
identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Bai 7

In [4]:
import numpy as np

# Tạo mảng 10 phần tử trong khoảng [15, 55]
array_range = np.linspace(15, 55, 10)
print("Mảng đầy đủ:")
print(array_range)

# In các giá trị ngoại trừ phần tử đầu và cuối
print("\nCác giá trị ngoại trừ phần tử đầu và cuối:")
print(array_range[1:-1])

Mảng đầy đủ:
[15.         19.44444444 23.88888889 28.33333333 32.77777778 37.22222222
 41.66666667 46.11111111 50.55555556 55.        ]

Các giá trị ngoại trừ phần tử đầu và cuối:
[19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]

Bai 8

In [ ]:
import numpy as np

# Tạo mảng 20 phần tử trong khoảng [0, 20]
arr = np.linspace(0, 20, 20)
print("Mảng ban đầu:")
print(arr)

# Đổi dấu những số nằm trong khoảng [9, 15]
arr[(arr >= 9) & (arr <= 15)] *= -1

print("\nMảng sau khi đổi dấu các phần tử trong khoảng [9, 15]:")
print(arr)

Bai 9

In [ ]:
import numpy as np

# Tạo ma trận 3x4 với các phần tử ngẫu nhiên trong khoảng [10, 21]
matrix_3x4 = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4 với các giá trị trong khoảng [10, 21]:")
print(matrix_3x4)

Bai 10

In [ ]:
import numpy as np

# Tạo ma trận 10x10 toàn số 1
border_matrix = np.ones((10, 10))

# Gán các phần tử bên trong (từ hàng 1 đến 8 và cột 1 đến 8) bằng 0
border_matrix[1:-1, 1:-1] = 0

print("Ma trận 10x10 với biên bằng 1 và bên trong bằng 0:")
print(border_matrix)

Bai 11

In [ ]:
import numpy as np

# Tạo mảng chứa các giá trị cho đường chéo chính
diagonal_values = [1, 2, 3, 4, 5]

# Sử dụng hàm np.diag để tạo ma trận
diagonal_matrix = np.diag(diagonal_values)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(diagonal_matrix)

Bai 12

In [ ]:
import numpy as np

# Tạo mảng 3x3x3 với các số nguyên ngẫu nhiên từ 1 đến 10
array_3d = np.random.randint(1, 11, size=(3, 3, 3))
print("Mảng 3x3x3:")
print(array_3d)

# Tính tổng theo mỗi dòng (axis=2 cho mảng 3 chiều)
row_sum = np.sum(array_3d, axis=2)
print("\nTổng theo mỗi dòng (mỗi ma trận 2D con):")
print(row_sum)

# Tính tổng theo mỗi cột (axis=1 cho mảng 3 chiều)
col_sum = np.sum(array_3d, axis=1)
print("\nTổng theo mỗi cột (mỗi ma trận 2D con):")
print(col_sum)

Bai 13

In [ ]:
import numpy as np

# Tạo 2 vector ngẫu nhiên 10 phần tử
vector_a = np.random.rand(10)
vector_b = np.random.rand(10)

print("Vector a:", vector_a)
print("Vector b:", vector_b)

# Thực hiện inner product (np.dot)
inner_product = np.dot(vector_a, vector_b)

print("\nTích vô hướng (Inner Product) của a và b:", inner_product)

Bai 14

In [ ]:
import numpy as np

# Tạo ma trận A kích thước 4x3 với các giá trị ngẫu nhiên
A = np.random.randint(1, 10, size=(4, 3))
# Tạo vector y gồm 3 phần tử ngẫu nhiên
y = np.random.randint(1, 10, size=3)

print("Ma trận A (4x3):")
print(A)
print("\nVector y (3 phần tử):")
print(y)

# Cộng vector y vào từng dòng của A (Broadcasting)
result = A + y

print("\nKết quả sau khi cộng y vào từng dòng của A:")
print(result)

Bai 15

In [ ]:
import pandas as pd

# Tạo 2 Series
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", s1)
print("\nSeries 2:\n", s2)

# Thực hiện các phép toán
print("\nCộng (s1 + s2):\n", s1 + s2)
print("\nTrừ (s1 - s2):\n", s1 - s2)
print("\nNhân (s1 * s2):\n", s1 * s2)
print("\nChia (s1 / s2):\n", s1 / s2)

Bai 16

In [5]:
import pandas as pd

# Tạo một DataFrame mẫu
data = {
    'Cột 1': [10, 20, 30, 40],
    'Cột 2': [5, 15, 25, 35]
}
df = pd.DataFrame(data)
print("DataFrame ban đầu:")
display(df)

# Chuyển đổi cột đầu tiên thành Series sử dụng .iloc (thay thế cho .ix)
first_col_series = df.iloc[:, 0]

print("\nCột đầu tiên dưới dạng Series:")
print(first_col_series)
print("Kiểu dữ liệu:", type(first_col_series))

DataFrame ban đầu:

   Cột 1  Cột 2
0     10      5
1     20     15
2     30     25
3     40     35

Cột đầu tiên dưới dạng Series:
0    10
1    20
2    30
3    40
Name: Cột 1, dtype: int64
Kiểu dữ liệu: <class 'pandas.core.series.Series'>

Bai 17

In [7]:
import pandas as pd
import numpy as np

# Tạo DataFrame 4x3 với các giá trị ngẫu nhiên
df_random = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)), columns=['A', 'B', 'C'])
print("DataFrame ban đầu:")
display(df_random)

# Sắp xếp theo cột 'A'
df_sorted = df_random.sort_values(by='A')

print("\nDataFrame sau khi sắp xếp theo cột A:")
display(df_sorted)

DataFrame ban đầu:

    A   B   C
0  98  40  29
1  36  77  69
2  66  79  28
3  23  69  43

DataFrame sau khi sắp xếp theo cột A:

    A   B   C
3  23  69  43
1  36  77  69
2  66  79  28
0  98  40  29

Bai 18

In [ ]:
import pandas as pd

# Lấy cột 'A' từ df_random để làm Series
series_a = df_random['A']
print("Series gốc (từ cột A):")
print(series_a)

# Định nghĩa index mới (ví dụ: đổi từ 0,1,2,3 thành các nhãn chữ)
new_index = ['Row_1', 'Row_2', 'Row_3', 'Row_4']

# Sử dụng reindex
# Lưu ý: reindex thường dùng để khớp dữ liệu với một tập nhãn mới.
# Nếu chỉ muốn gán lại nhãn, ta có thể dùng series.index = new_index
# Ở đây ta minh họa reindex bằng cách gán lại giá trị index cũ sang nhãn mới
series_reindexed = series_a.copy()
series_reindexed.index = new_index

print("\nSeries sau khi thay đổi Index:")
print(series_reindexed)

Bai 19

In [ ]:
import pandas as pd

# Khởi tạo 2 Series theo dữ liệu mẫu
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:")
print(sr1)
print("\nsr2:")
print(sr2)

# Tìm các phần tử trong sr1 không có trong sr2 dùng isin()
# ~ là toán tử phủ định (không nằm trong)
result = sr1[~sr1.isin(sr2)]

print("\nItems of sr1 not present in sr2:")
print(result)

Bai 20

In [ ]:
import numpy as np
import pandas as pd

# Tạo 2 Series x và y ngẫu nhiên gồm 20 số nguyên từ 1 đến 30
x = pd.Series(np.random.randint(1, 31, 20))
y = pd.Series(np.random.randint(1, 31, 20))

print("Series x:")
print(x.values)
print("\nSeries y:")
print(y.values)

# 1. numpy.intersect1d: Tìm các phần tử chung (Giao)
intersect_result = np.intersect1d(x, y)
print("\nPhép giao (intersect1d) - Các phần tử có ở cả x và y:")
print(intersect_result)

# 2. numpy.union1d: Tìm tất cả phần tử duy nhất từ cả hai (Hội)
union_result = np.union1d(x, y)
print("\nPhép hội (union1d) - Tất cả phần tử duy nhất từ cả x và y:")
print(union_result)

Bai 21

In [ ]:
import pandas as pd

# Tạo Series x và y theo mẫu của bạn
x = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], name='x')
y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'], name='y')

print("Series x:")
print(x)
print("\nSeries y:")
print(y)

# 1. Thêm theo chiều dọc (Vertical stacking)
# Lưu ý: pd.concat mặc định axis=0
vertical_concat = pd.concat([x, y], axis=0)
print("\nKết hợp theo chiều dọc (Vertical):")
print(vertical_concat)

# 2. Thêm theo chiều ngang (Horizontal stacking)
# Kết quả sẽ là một DataFrame
horizontal_concat = pd.concat([x, y], axis=1)
print("\nKết hợp theo chiều ngang (Horizontal) - Tạo DataFrame:")
display(horizontal_concat)

Bai 22

In [ ]:
import pandas as pd
import numpy as np

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Tạo DataFrame
df = pd.DataFrame(exam_data, index=labels)

print("Dữ liệu bài kiểm tra:")
display(df)